import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { api, type MarketSignal } from "../lib/api";
import { useFilters } from "../state/FilterContext";
import { Card, EmptyState, ErrorState, LoadingSkeleton, SignalBadge } from "../components/ui";

/** Signal text is generated server-side with the exact entity name (area,
 * sub-area or community) interpolated verbatim into the sentence — e.g.
 * "...rental contracts in Al Yufrah 2 over the last 90d." Splitting on that
 * exact substring turns just the entity name into a link to its community
 * page, without needing to parse the sentence structure. */
function SignalText({ signal }: { signal: MarketSignal }) {
  const name = signal.evidence.community ?? signal.evidence.area;
  const key = signal.evidence.community_key;
  if (!name || !key || !signal.text.includes(name)) return <>{signal.text}</>;
  const idx = signal.text.indexOf(name);
  const before = signal.text.slice(0, idx);
  const after = signal.text.slice(idx + name.length);
  return (
    <>
      {before}
      <Link to={`/communities/${encodeURIComponent(key)}`} className="text-[var(--accent)] hover:underline font-medium">
        {name}
      </Link>
      {after}
    </>
  );
}

const CATEGORY_LABELS: Record<string, string> = {
  dominant_unit_demand: "Dominant Unit Demand",
  rental_activity_growth: "Rental Activity Growth",
  project_momentum: "Project Momentum",
  rent_growth_flat_price: "Rent Growth vs Flat Price",
  supply_demand_imbalance: "Supply / Demand Imbalance",
};

const CATEGORY_TONE: Record<string, "good" | "warn" | "neutral"> = {
  dominant_unit_demand: "neutral",
  rental_activity_growth: "good",
  project_momentum: "good",
  rent_growth_flat_price: "good",
  supply_demand_imbalance: "warn",
};

export function MarketSignals() {
  const { period } = useFilters();
  const { data, isLoading, error } = useQuery({ queryKey: ["signals", period], queryFn: () => api.signals(period, 6) });

  if (isLoading) return <LoadingSkeleton rows={6} />;
  if (error) return <ErrorState message={(error as Error).message} />;
  if (!data) return null;

  const grouped = data.signals.reduce<Record<string, MarketSignal[]>>((acc, s) => {
    (acc[s.category] ??= []).push(s);
    return acc;
  }, {});

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Market Signals</h1>
        <p className="text-xs text-[var(--text-muted)] mt-1">
          Deterministic observations calculated directly from the data — not predictions, and not generated by an LLM. Every signal requires at
          least {data.min_sample} observations in the relevant window before it's surfaced.
        </p>
      </div>

      {data.signals.length === 0 && (
        <EmptyState title="No signals meet the sample-size threshold this period" detail="Try a longer period (e.g. 6M) from the period selector above." />
      )}

      {Object.entries(grouped).map(([category, signalsList]) => (
        <Card key={category} className="p-4">
          <div className="flex items-center gap-2 mb-3">
            <h2 className="text-sm font-semibold uppercase tracking-wide">{CATEGORY_LABELS[category] ?? category}</h2>
            <SignalBadge tone={CATEGORY_TONE[category] ?? "neutral"}>{signalsList.length}</SignalBadge>
          </div>
          <ul className="space-y-3">
            {signalsList.map((s, i) => (
              <li key={i} className="text-sm border-l-2 border-[var(--accent)] pl-3">
                <SignalText signal={s} />
              </li>
            ))}
          </ul>
        </Card>
      ))}
    </div>
  );
}
